dist: bionic
language: r
cache: packages
latex: false
warnings_are_errors: false
r_build_args: --no-build-vignettes
r_check_args: --as-cran --ignore-vignettes

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_: false
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

# This is the minimal set of R packages needed to run "R CMD check" on
# the package.
install:
  - R -e 'install.packages(c("assertthat","abind","mvtnorm","Rcpp","RcppArmadillo","RcppGSL","rmeta","plyr","testthat","devtools"))'
  - R -e 'devtools::install_github("stephens999/ashr")'

before_install:
  - sudo apt-get install -y libgsl0-dev libomp-dev
      
r_packages:
  - covr

r_github_packages: stephens999/ashr
  
after_success:
  - Rscript -e 'covr::codecov()'

branches:
  only:
  - master
